In [1]:
import numpy as np

%matplotlib inline

In [2]:
import pandas as pd

In [3]:
ped_df = pd.read_csv("pheno.ped", sep="\t")

In [4]:
len(ped_df)

195

In [5]:
ped_df.head()

  familyId personId   dadId   momId  sex  status role
0       f1   f1.dad       0       0    1       1  dad
1       f1   f1.mom       0       0    2       1  mom
2       f1    f1.s1  f1.dad  f1.mom    2       1  sib
3       f1    f1.p1  f1.dad  f1.mom    1       2  prb
4       f1    f1.s2  f1.dad  f1.mom    2       2  sib

In [6]:
dates_p1 = pd.Series(np.random.randint(2, high=32, size=len(ped_df)))
dates_p2 = pd.Series(np.random.choice([" days", " weeks", " months", " years", " wks", " mos", " yrs", "M", "WK", "YR", "M.O", " Y.O"], size=len(ped_df)))
bckg_m1 = dates_p1.map(str) + dates_p2
bckg_m1.head()

0      16 wks
1    25 weeks
2      14 yrs
3         5WK
4     5 weeks
dtype: object

In [7]:
bckg_m2 = pd.Series(np.random.choice(["true", "false"], size=len(ped_df)))
bckg_m2.head()

0    false
1    false
2     true
3     true
4     true
dtype: object

In [8]:
bckg_m3 = pd.Series(np.random.rand(len(ped_df)))
bckg_m3.head()

0    0.371212
1    0.122486
2    0.638832
3    0.605689
4    0.769319
dtype: float64

In [9]:
bckg_m4 = pd.Series(np.random.choice(["true", "false"], size=len(ped_df)))
bckg_m4.head()

0     true
1    false
2     true
3    false
4    false
dtype: object

In [10]:
bckg_m5 = pd.Series(np.random.choice(["true", "false"], size=len(ped_df)))
bckg_m5.head()

0     true
1     true
2     true
3    false
4     true
dtype: object

In [11]:
weight_p1 = pd.Series(np.random.randint(50, high=140, size=len(ped_df)))
weight_p2 = pd.Series(np.random.choice([" KG", " Kg", " kg", " kilogrammes"], size=len(ped_df)))
bckg_m6 = weight_p1.map(str) + weight_p2
bckg_m6.head()

0             102 kg
1              68 kg
2     69 kilogrammes
3              54 Kg
4    128 kilogrammes
dtype: object

## Full background

In [19]:
bckg_df = pd.DataFrame(index=ped_df.index)

In [20]:
bckg_df["personId"] = ped_df["personId"]

In [21]:
bckg_df["m1"] = bckg_m1
bckg_df["m2"] = bckg_m2
# bckg_df['m3'] = bckg_m3
bckg_df["m4"] = bckg_m4
bckg_df["m5"] = bckg_m5
bckg_df["m6"] = bckg_m6

In [22]:
194 * 6

1164

In [23]:
# delete random entries of varying length in the dataframe
for i in range(200):
    start_col = np.random.randint(1, 7)
    del_len = np.random.randint(1, (7 - start_col) + 1)
    entry = np.random.randint(1, len(ped_df))

    for k in range(start_col, start_col + del_len):
        bckg_df.at[entry, f"m{k!s}"] = np.NaN

In [24]:
bckg_df

    personId         m1     m2     m4     m5               m6  m3
0     f1.dad     16 wks  false   true   true           102 kg NaN
1     f1.mom   25 weeks  false    NaN    NaN              NaN NaN
2      f1.s1     14 yrs   true   true   true   69 kilogrammes NaN
3      f1.p1        NaN    NaN    NaN    NaN              NaN NaN
4      f1.s2    5 weeks   true    NaN    NaN              NaN NaN
5     f2.mom   7 months    NaN  false  false            98 KG NaN
6     f2.dad        NaN    NaN   true  false            62 Kg NaN
7      f2.p1      8 yrs   true  false  false              NaN NaN
8      f2.s1     16 wks    NaN    NaN    NaN              NaN NaN
9     f3.dad      17M.O  false   true   true              NaN NaN
10    f3.mom      3 wks  false   true   true           102 kg NaN
11     f3.p1     25 wks   true   true  false           129 KG NaN
12     f3.s1       28WK  false   true  false  112 kilogrammes NaN
13     f3.s2        NaN    NaN    NaN    NaN              NaN NaN
14     f3.s3    2 years   true    NaN    NaN           126 KG NaN
15    f4.dad      2 Y.O  false  false  false            64 kg NaN
16    f4.mom      4 yrs  false  false   true           119 Kg NaN
17     f4.s1       27WK   true    NaN    NaN              NaN NaN
18     f4.p1   22 weeks   true   true  false            72 kg NaN
19     f4.s2   4 months    NaN    NaN    NaN              NaN NaN
20    f5.mom        23M  false    NaN    NaN            80 kg NaN
21    f5.dad     8 days  false   true  false            59 Kg NaN
22     f5.p1     25 mos    NaN    NaN    NaN              NaN NaN
23     f5.s1        NaN    NaN    NaN    NaN           107 kg NaN
24    f6.dad     26 yrs  false   true   true            72 kg NaN
25    f6.mom       25WK  false   true   true            71 KG NaN
26     f6.p1     19 wks   true   true  false           108 KG NaN
27     f6.s1        NaN    NaN    NaN    NaN              NaN NaN
28     f6.s2      2 wks    NaN    NaN    NaN            76 KG NaN
29     f6.s3        NaN    NaN    NaN    NaN              NaN NaN
..       ...        ...    ...    ...    ...              ...  ..
165  f34.dad   13 years  false    NaN    NaN              NaN NaN
166  f34.mom      6 Y.O   true  false   true              NaN NaN
167   f34.s1     10 mos   true    NaN    NaN              NaN NaN
168   f34.p1        NaN    NaN    NaN    NaN              NaN NaN
169   f34.s2   17 years    NaN    NaN    NaN              NaN NaN
170  f35.mom     29 Y.O  false    NaN  false           134 Kg NaN
171  f35.dad       25WK  false   true   true            88 Kg NaN
172   f35.p1      20M.O   true  false    NaN              NaN NaN
173   f35.s1    5 years  false  false  false  109 kilogrammes NaN
174  f36.dad  11 months   true    NaN   true              NaN NaN
175  f36.mom        NaN    NaN    NaN  false              NaN NaN
176   f36.p1       16YR   true  false  false   77 kilogrammes NaN
177   f36.s1      20M.O   true    NaN   true              NaN NaN
178   f36.s2       6M.O  false   true   true              NaN NaN
179   f36.s3  31 months   true  false   true  132 kilogrammes NaN
180  f37.dad       9M.O  false  false  false           106 Kg NaN
181  f37.mom   15 weeks   true   true  false              NaN NaN
182   f37.s1        NaN   true   true  false            94 kg NaN
183   f37.p1     16 mos  false    NaN    NaN   50 kilogrammes NaN
184   f37.s2        NaN    NaN    NaN    NaN            88 kg NaN
185  f38.mom     11 yrs  false   true    NaN            75 kg NaN
186  f38.dad    3 years   true   true   true  124 kilogrammes NaN
187   f38.p1   18 years  false  false  false           109 kg NaN
188   f38.s1   11 years  false  false   true           118 Kg NaN
189  f39.dad     19 mos   true  false   true           128 Kg NaN
190  f39.mom     14 Y.O   true   true  false            53 Kg NaN
191   f39.p1       8M.O   true  false   true            67 kg NaN
192   f39.s1    2 years  false   true  false           131 Kg NaN
193   f39.s2        NaN    NaN  false   true   62 kilogrammes NaN
194   f39.s3  23 months  false  false  false            69 KG NaN

[195 rows x 7 columns]

In [25]:
bckg_df.to_csv("background.csv", index=False)